steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/python-app/python-app:latest', '.']

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/python-app/python-app:latest']

  # Step 3: Deploy on VM using Docker
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - my-python-vm
      - --zone=us-central1-a
      - --
      - -l
      - sa_950066490868
      - --command
      - |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo docker stop python-app || true
        sudo docker rm python-app || true
        sudo docker run -d -p 80:5000 --name python-app us-central1-docker.pkg.dev/$PROJECT_ID/python-app/python-app:latest

timeout: "1200s"

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/python-app/python-app:latest'
